---
language: ruby
script: "rake validate"
matrix:
  include:
    - rvm: 2.3.1
      env: PUPPET_VERSION=4.7.0
    - rvm: 2.1.5
      env: PUPPET_VERSION=3.8.6 FUTURE_PARSER=yes
    - rvm: 2.1.5
      env: PUPPET_VERSION=3.8.6
